---
- hosts: all
  become: true
  vars:
    java_version: "7u51-2.4.*"
    spark_version: "2.0.0-bin-hadoop2.7"
    anaconda_make_sys_default: true
    anaconda_ver: '4.2.0'
    spark_defaults_extras:
      spark.driver.memory: "{{ (ansible_memtotal_mb*0.75)|int|abs }}m"

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes
    - name: Install Java
      apt: name=openjdk-8-jdk state=present

  tasks:
    - name: Add spark bin to PATH
      with_items:
        - etc/profile.d/spark.sh
      template:
        src: '{{item}}.j2'
        dest: /{{item}}
        mode: '0644'

  roles:
    - azavea.spark
    - andrewrothstein.anaconda
